SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE USER_FRIEND RESTART IDENTITY;
TRUNCATE TABLE FILM_GENRE RESTART IDENTITY;
TRUNCATE TABLE GENRE RESTART IDENTITY;
TRUNCATE TABLE FILM_LIKE RESTART IDENTITY;
TRUNCATE TABLE FILMS RESTART IDENTITY;
TRUNCATE TABLE RATING RESTART IDENTITY;
TRUNCATE TABLE USERS RESTART IDENTITY;
SET REFERENTIAL_INTEGRITY TRUE;

INSERT INTO genre (name)
VALUES ('Комедия'),
       ('Драма'),
       ('Мультфильм'),
       ('Триллер'),
       ('Документальный'),
       ('Боевик');

INSERT INTO RATING (name)
VALUES ('G'),
       ('PG'),
       ('PG-13'),
       ('R'),
       ('NC-17');